#!/usr/bin/env python3
"""Generate wakeword_list.md from the bundled WakeNet model metadata."""

import argparse
import re
from datetime import datetime
from pathlib import Path
from typing import Tuple


COMPONENT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_MODEL_DIR = COMPONENT_DIR / "model" / "wakenet_model"
DEFAULT_OUTPUT = COMPONENT_DIR / "wakeword_list.md"

MODEL_INFO_PATTERN = re.compile(
    r"^.+_(?P<wake_word>[^_]+)_\d+_[0-9.]+_[0-9.]+$",
    re.IGNORECASE,
)

WAKE_WORD_ALIASES = {
    "alexa": "Alexa",
    "Bonjourespfr": "Bonjour ESP",
    "hey buddy": "Hey,Buddy",
    "heyhermes": "Hey,Hermes",
    "heynova": "Hey,Nova",
    "hiesp": "Hi,ESP",
    "Konnichihaespja": "こんにちは ESP",
    "Linaiban": "璃奈板",
    "mosaico": "Mosaico",
    "Ni3Hao3Xiao3Rui4": "你好小瑞",
    "Ni3Hao3Xiao3Zhi4": "你好小智",
    "tu2tu2ni3hao3": "涂涂你好",
    "Xiaoaitongxue": "小爱同学",
    "hitelly": "Hi, Telly",
    "nihaoxiaoan": "你好小安",
    "嗨乐鑫": "Hi,乐鑫",
    "嗨，乐鑫": "Hi,乐鑫",
}
WAKE_WORD_ALIASES_NORM = {key.casefold(): value for key, value in WAKE_WORD_ALIASES.items()}


def read_wake_word(model_dir: Path) -> str:
    """Read and validate the wake word from a model's metadata files."""
    wake_words = set()
    info_files = sorted(model_dir.glob("_MODEL_INFO*"))
    if not info_files:
        raise ValueError(f"No _MODEL_INFO file found in {model_dir}")

    for info_file in info_files:
        for raw_line in info_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            match = MODEL_INFO_PATTERN.match(line)
            if not match:
                raise ValueError(f"Cannot parse model metadata: {info_file}: {line}")
            wake_words.add(match.group("wake_word"))

    if len(wake_words) != 1:
        raise ValueError(
            f"Expected one wake word in {model_dir}, found: {sorted(wake_words)}"
        )

    wake_word = wake_words.pop()
    return WAKE_WORD_ALIASES_NORM.get(wake_word.casefold(), wake_word)


def model_sort_key(item: Tuple[str, str]) -> Tuple[int, str, str]:
    """Sort model IDs by WakeNet version, variant, and name."""
    model_name = item[0]
    match = re.match(r"wn(\d+)([a-z]*)(.*)", model_name)
    if not match:
        return (999, "", model_name)
    return (int(match.group(1)), match.group(2), match.group(3))


def escape_markdown(value: str) -> str:
    return value.replace("|", r"\|")


def generate_document(model_dir: Path) -> str:
    models = [
        (path.name, read_wake_word(path))
        for path in model_dir.iterdir()
        if path.is_dir()
    ]
    models.sort(key=model_sort_key)

    lines = [
        "# Supported Wake Word Models",
        "",
        "<!-- Generated by tool/generate_wakeword_list.py. Do not edit manually. -->",
        "",
        "This file lists all WakeNet models bundled with ESP-SR. The model files are "
        "stored in [`model/wakenet_model`](model/wakenet_model/).",
        "",
        "> **Note:** Most wake word models are automatically generated and tested "
        "using the TTS pipeline. Their generalization performance cannot be fully "
        "guaranteed. Evaluate each model thoroughly in its intended environment "
        "before commercial use.",
        "",
        "## Loading a Wake Word Model",
        "",
        "There are two ways to load a wake word model:",
        "",
        "1. **Load models from an external path.** Run `idf.py menuconfig`, open "
        "`ESP Speech Recognition`, and set `Load models from external path` "
        "(`ESP_SR_EXTERNAL_MODEL_PATH`) to a directory containing one or more model "
        "folders. This directory can be located anywhere on the build host. Each "
        "model folder must contain a valid `_MODEL_INFO_` file and the required "
        "model data. During the build, CMake automatically packages all valid models "
        "found at this path into the model partition.",
        "2. **Add a menuconfig entry for a model bundled with ESP-SR.** The model "
        "folder must be placed under `esp-sr/model/wakenet_model`. Add a `bool` entry "
        "to the appropriate `Load Multiple Wake Words` menu in `Kconfig.projbuild`. "
        "Name the symbol `SR_WN_<MODEL_FOLDER_NAME_IN_UPPERCASE>` so that it maps to "
        "the folder name. For example, the folder `wn9_my_wake_word` must use "
        "`SR_WN_WN9_MY_WAKE_WORD`. Select the new entry in menuconfig and rebuild "
        "the application; CMake will package the selected model automatically.",
        "",
        "## Wake Word List",
        "",
        "| Wake word | Model name |",
        "|:----------|:-----------|",
    ]
    lines.extend(
        f"| {escape_markdown(wake_word)} | `{escape_markdown(model_name)}` |"
        for model_name, wake_word in models
    )
    lines.extend(
        [
            "",
            f"Generated at: {datetime.now().astimezone().isoformat(timespec='seconds')}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the complete ESP-SR wake word model list."
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        default=DEFAULT_MODEL_DIR,
        help=f"WakeNet model directory (default: {DEFAULT_MODEL_DIR})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Markdown output path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args()

    args.output.write_text(
        generate_document(args.model_dir.resolve()),
        encoding="utf-8",
    )
    print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
